# Dockerfile-rest
FROM python:3.11-slim
WORKDIR /app
COPY rest/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY rest/rest-server.py .
EXPOSE 5000
CMD ["python","rest-server.py"]
